### ISSUE TITLE
mode state isn't saved when the buffer is changed.

### ISSUE THREAD

**Issue by kain88-de** [mrkkrp/modalka#5] opened 2015-09-20 20:23 UTC
Evil saves the state a buffer was last in. So when I'm in insert mode in buffer <1> when I leave it I'm still in insert-mode when I switch back to buffer <1>.

With Modalka I'm always in modalka-mode when I switch to a buffer regardless of what has been set before.  This is very irritating when I quickly switch to another buffer to look something up.

**Comment by mrkkrp** [comment] 2015-09-20 20:33
@kain88-de, Modalka is a minor mode. This means that it is enabled/disabled on per-buffer basis.

> Evil saves the state a buffer was last in. So when I'm in insert mode in buffer <1> when I leave it I'm still in insert-mode when I switch back to buffer <1>.

This is how Modalka currently works. In fact, any other behavior would be harder to achieve.

> With Modalka I'm always in modalka-mode when I switch to a buffer regardless of what has been set before. This is very irritating when I quickly switch to another buffer to look something up.

I cannot reproduce this. Can you describe, step by step, starting with `emacs -Q` how the problem you're experiencing can be reproduced?

**Comment by kain88-de** [comment] 2015-09-20 21:01
OK I see that the problem are the hooks recommended in the README.md
```lisp
(add-hook 'prog-mode-hook #'modalka-mode)
```
Without these lines in my `init.el` everything works like I expect. OK it will take a little bit getting used to to have 'insert-mode' as default.

It would be nice though to have 'modalka-mode` enabled when I open a new buffer and keep track of the state otherwise.

**Comment by mrkkrp** [comment] 2015-09-21 08:28
@kain88-de, This hook enables the mode when you open (create) new buffer with major mode that has something to do with programming. I use these hooks myself and it does keep "state". Unless you want to preserve state when you kill/reopen buffer (?)

**Comment by mrkkrp** [comment] 2015-10-02 15:35
Closing the issue, since it's not clear what I can do about it. Probably some misunderstanding takes place. I have no idea how this doesn't keep state for you. If you want to reopen, describe clearly, step by step, staring with `emacs -Q` (that is, without loading of configuration), how to reproduce your problem. Please state what happened and what *exactly you expected to happen instead*. In its current state, this issue complains about problem that is very unlikely to be fault of this package.

**Closed by mrkkrp** 2015-10-02 15:35 UTC
Labels: unconfirmed
